### ISSUE TITLE
[Feature]Integration of chatgpt with Smart select feature extraction,

### ISSUE THREAD

**Issue by litesh1123** [recodehive/Scrape-ML#140]
**Describe the bug**
Do smart scrapping with help of AI
Text is extracted from a screenshot but with the help of Openai 
> We can understand extracted text
>optimize output
Example: like the users screenshot or image is not clear little blur can extract only some meaningful info but with the help of chatpt and user's context being set like what screenshot is about  ,what text it has it will help in understanding extracted text and also generate relevant content to user. Which may be really very helpful

User ha to interact with GUI interface and give these things:-
>input screenshot image
>give the open API key of user
>give context what this screenshot is about
>give prompt like what he is expecting
>set expected number of lines  output must be 
>temperature of gpt
>advanced feature for pro users what engiene he wnat to use like  gpt4 , gpt3.5 plus etc

**Comment by litesh1123** [comment]
@sanjay-kv please assign me this issue sir

**Comment by sanjay-kv** [comment]
can you relate somehow with current ongoing imdb review features

**Comment by litesh1123** [comment]
@sanjay-kv sir I have gone through imdb reviews I can add some more things like from reviews using nlp and also chatgpt embedding  ,we can know exactly like what users are feeling like are the movies interesting,boring etc I can raise new issue sir but 
The above issue i raised is Addition for smart select feature I have sent demo video and also done pr please check it

**Comment by litesh1123** [comment]
@sanjay-kv please reopen the issue 
I am trying for other alternative of gpt so tool some time will update ij next 5 days

**Comment by litesh1123** [comment]
updated code
