### ISSUE TITLE
Improve Product Listing Script: Code Optimization and Bug Fixes

### ISSUE THREAD

**Issue by bhanushri12** [recodehive/Scrape-ML#167]
Hi @sanjay-kv ,

I have identified several improvements and optimizations for the product listing script. I would like to work on this issue and implement the proposed changes. Could you please assign this issue to me?

Thank you!

**Comment by bhanushri12** [comment]
@sanjay-kv Can I be assigned this?

**Comment by Samik123Mit** [comment]
pls, assign me the issue. I will make sure the task is done.

**Comment by Taranpreet10451** [comment]
@sanjay-kv Please assign this to me.

**Comment by bhanushri12** [comment]
@sanjay-kv Can I start working on this?

**Comment by sanjay-kv** [comment]
Yes @bhanushri12
