### ISSUE TITLE
Implement a Recommendation System for Movies Using Collaborative Filtering

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [recodehive/Scrape-ML#196]
Develop a movie recommendation system using collaborative filtering techniques. Integrate it with the existing IMDB ratings analysis to provide personalized movie recommendations to users.

**Comment by pranjalbhawsar11** [comment]
Can I be assigned this issue?

**Comment by sanjay-kv** [comment]
@AKSHITHA-CHILUKA i hope you keep tracking of the contribution score from this repo, as this has limitations.

**Comment by AKSHITHA-CHILUKA** [comment]
I just got 50 points so I rased an issue

**Comment by AKSHITHA-CHILUKA** [comment]
Can you add a label to this issue sir I am still left with 10 points
