### ISSUE TITLE
Earthquake Prediction 

### ISSUE THREAD

**Issue by adityasingh-0803** [recodehive/Scrape-ML#201]
Using Naive bayes theorem, svm, random forest we can estimate the sesimic of earthquake. Although no one can predict when will earthquake will occur at what time though we can get sesimicity about the region and its region of destruction. 
Kindly assign me with necessary labels

**Comment by PadmalathaKasireddy** [comment]
im very eaiger to contribute for this issue , please assign me this issue.

warm regards,
padmalatha kasireddy

**Comment by tkshsbcue** [comment]
i would like to work on this issue

**Comment by tkshsbcue** [comment]
@sanjay-kv
