### ISSUE TITLE
Include Movie Posters in Recommendations

### ISSUE THREAD

**Issue by Shravya016** [recodehive/Scrape-ML#209]
I am proposing to include posters in the recommendation page, which currently only displays Wikipedia and trailer links. I have experience with a similar project where movie posters were included in the recommendations, enhancing the user experience.

![image](https://github.com/Recode-Hive/Scrape-ML/assets/98455300/2aaa1fe3-07a2-4b2d-b8cb-2db7886e80ef)

Currently, the recommendations only display Wikipedia and trailer links, which lack visual appeal and may not engage users effectively. Including movie posters will provide a more visually appealing and informative experience for users. This change will enhance the user interface and make the recommendations more engaging, ultimately benefiting the community by improving the usability and attractiveness of the project.

**Comment by sanjay-kv** [comment]
This is good development
