### ISSUE TITLE
Change the stats on reademe

### ISSUE THREAD

**Issue by sanjay-kv** [recodehive/Scrape-ML#227]
![image](https://github.com/user-attachments/assets/eb5671fe-0bd8-4fd8-a61c-968eecd80a04)

The stat readme links to another page need to fix this.

**Comment by SanskarSinghiit** [comment]
Hello @sanjay-kv 
Can I help you fix this.? Can you tell me which links are incorrrect.
I see the following links.
https://github.com/recodehive/Scrape-ML#contributors-   all contributors - 
https://github.com/recodehive/awesome-github-profiles/stargazers  Stars -
https://github.com/recodehive/awesome-github-profiles/network/members  Forks -   
https://github.com/recodehive/awesome-github-profiles/pulls  pull requests -
https://github.com/recodehive/awesome-github-profiles/issues  issues -     
https://github.com/recodehive/awesome-github-profiles/graphs/contributors  contributors -  
https://github.com/recodehive/awesome-github-profiles/blob/main/LICENSE  license -  
https://visitcount.itsvg.in/  Profile Views -
