### ISSUE TITLE
[Feature Request]: Hover Animation

### ISSUE THREAD

**Issue by Varun-malviya5** [recodehive/Scrape-ML#236]
It will make the website more interesting to use

**Comment by Varun-malviya5** [comment]
i have been trying to add the feature of hover animation but cant find the css file to add features in , moreover threre is no js file also ,please tell where to add the code because in my previous contribution there used to be a js and css file where i can make changes but here the case is different , please guide me

**Comment by sanjay-kv** [comment]
yes its basically a streamlit app. the files will be in app folder
