### ISSUE TITLE
ADD  Changelog Page

### ISSUE THREAD

**Issue by shubhagarwal1** [recodehive/Scrape-ML#276]
**Purpose:** 
Display recent updates and changes made to the app.

**Features:**
- List of recent updates or versions with release notes.
- Link each change to related issues or pull requests.
- Optional: Include a “Coming Soon” section for upcoming features.

**Comment by sanjay-kv** [comment]
@shubhagarwal1 

https://gssoc.girlscript.tech/update

you can do simillar to this.

**Comment by sanjay-kv** [comment]
let me know if you need to codebase?
