### ISSUE TITLE
ADD HACKTOBERFEST -ACCEPTED AND GSSOC LABELS ON MAIN PAGE

### ISSUE THREAD

**Issue by alo7lika** [recodehive/Scrape-ML#284]
**Describe the bug**
LABELS "HACKTOBERFEST -ACCEPTED" AND "GSSOC" ARE NECESSARY FOR THE REPOSITORY TO PARTICIPATE 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2024-10-25 181650](https://github.com/user-attachments/assets/55d63f11-d6ef-42d3-a31f-480e57ffd1ba)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alo7lika** [comment]
@sanjay-kv

**Comment by sanjay-kv** [comment]
not required
