### ISSUE TITLE
Issue Report: OCR Accuracy and Error Handling in Web Scraping Script

### ISSUE THREAD

**Issue by PrashantKumar39** [recodehive/Scrape-ML#97]
To Recode-Hive,

I hope you're well. I've reviewed our web scraping script and identified two key areas for improvement:

1. OCR Accuracy: Inconsistent text extraction due to varying screenshot quality and webpage content complexity.

Solution: Implement image preprocessing and optimize Tesseract configuration.

2. Error Handling and Logging: Minimal error handling hindering script stability and debugging.

Solution: Enhance error handling with detailed logging and exception handling.

Thank you

**Comment by sanjay-kv** [comment]
@litesh1123 Hi, He found some area of improvement on your work, I would like to know your opinion before assigning to him.

**Comment by litesh1123** [comment]
@sanjay-kv sir yes these issues are genuine and hope this can increase accuracy and optimize it
thank you @PrashantKumar39 for raising issue would love to see your contribution in optimizing ocr extrcation

**Comment by sanjay-kv** [comment]
Can you be a collaborator and get github collab badge? I will add you into the issue as well.

**Comment by litesh1123** [comment]
@sanjay-kv yes sir it would be great , i would like to collab

**Comment by litesh1123** [comment]
@sanjay-kv sir if possible please open this issue
Pr i have done  has conflicts , I will resolve and do pr

**Comment by litesh1123** [comment]
@sanjay-kv tyank you sir

**Comment by litesh1123** [comment]
@sanjay-kv  sir , 
fine tuning during ocr extraction is done .
this is drive link  video of how   code's functioning and its output 
 https://drive.google.com/file/d/1phb0gmf1UlSvp7tU80azUM3PQH9Wo3f1/view?usp=sharing

if possible please open issue sir , i wil do pr
